### ISSUE TITLE
typo in Makefile.in

### ISSUE THREAD

**Issue by valkenlee** [pivasoftware/microxml#3]
```
# git diff Makefile.in 
diff --git a/Makefile.in b/Makefile.in
index 3ecf7ad..a2dc351 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -155,7 +155,7 @@ install-libmicroxml.so.1.0:
        $(RM) $(BUILDROOT)$(libdir)/libmicroxml.so
        $(LN) libmicroxml.so.1.0 $(BUILDROOT)$(libdir)/libmicroxml.so
        $(RM) $(BUILDROOT)$(libdir)/libmicroxml.so.1
-       $(LN) libmicroxml.so.1.o $(BUILDROOT)$(libdir)/libmicroxml.so.1
+       $(LN) libmicroxml.so.1.0 $(BUILDROOT)$(libdir)/libmicroxml.so.1
 
 install-libmicroxml.sl.1:
        echo Installing libmicroxml.sl to $(BUILDROOT)$(libdir)...
```

**Comment by hmh** [comment]
That makefile is really broken, FWIW.  We work around that here by not using the install-* targets at all in our OpenWRT builds that use libmicroxml (for easycwmp), so we had never noticed the issue.

Likely, upstream does the same, so they did not notice the breakage either.

**Comment by hmh** [comment]
There's an open merge request/pull request about this...  #1

**Comment by valkenlee** [comment]
thank you for fixing.
It was a great help for a novice programmer who is not familiar with git.

**Comment by hmh** [comment]
(note that I am not part of microxml upstream or a member of pivasoftware, I just use it. But since there is an open pull request about this already, there is not much reason to reopen this issue since the open merge request also documents it as an issue)
